# Usa Ubuntu 16.10 como base
FROM ubuntu:16.10

# Actualiza los repositorios e instala el cliente OpenSSH
RUN apt-get update && apt-get install -y openssh-client

# Define el comando por defecto al iniciar el contenedor
CMD ["bash"]
